### PR TITLE
docs: ratify Drive Workspace canonical role

### LINKED ISSUE #32: Resolve Drive / Workspace role in canon
## Source
Architecture Normalization Issue 3 — derived from docs/10_meta/Architecture_Normalization_Targeted_Issue_List_2026-04-24.md

## Scope
Decide whether Drive / Workspace is mirror only or also an advisory ingress adapter.

## Source docs
- docs/00_foundations/LifeOS Target Architecture v2.3c.md
- docs/00_foundations/ARCH_Multi_Agent_Communication_Architecture.md
- artifacts/googleforcoo.md

## Acceptance criteria
- [ ] Canonical role chosen (mirror-only vs advisory ingress)
- [ ] Proposal-only surfaces kept proposal-only unless ratified
- [ ] Google Workspace / gws mention added only if documenting already-existing reality
- [ ] Briefing / ingress implications resolved

## Required repo surfaces before merge
- Canonical architecture docs
- docs/10_meta/ARCHITECTURE_SOURCE_OF_TRUTH.md
- Architecture changelog
- ADR if ratified

## Constraint
Do not implement Drive/Workspace advisory ingress unless explicitly ratified.

### LINKED ISSUE #34: Reconcile communications draft with canon or mark it proposal-only
## Source
Architecture Normalization Issue 5 — derived from docs/10_meta/Architecture_Normalization_Targeted_Issue_List_2026-04-24.md

## Scope
Either absorb ratified semantics into canon or clearly mark the communications draft as non-canonical.

## Target doc
docs/00_foundations/ARCH_Multi_Agent_Communication_Architecture.md

## Acceptance criteria
- [ ] No silent conflict remains on approval semantics, Drive role, or operational-state scope
- [ ] Status / supersession markers are explicit
- [ ] Stale statements are marked or removed

## Required repo surfaces before merge
- Affected architecture docs
- docs/10_meta/ARCHITECTURE_SOURCE_OF_TRUTH.md
- Architecture changelog
- Targeted ADRs only if ratified

## Constraint
Do not silently promote proposal-only semantics into canon.

### PR DESCRIPTION
**Pull request by marcusglee11**
## Summary

- Ratifies Drive / Workspace as a non-canonical collaboration, drafting, advisory, and briefing surface (ADR-004).
- Closes normalization blocker #2 in `ARCHITECTURE_SOURCE_OF_TRUTH.md`.
- Registers ADR-004 in the ADR index.

## Changes

- `docs/00_foundations/LifeOS Target Architecture v2.3c.md` — replaced §2.7 Google Drive stub with full canonical-role ratification section
- `docs/01_governance/COO_Operating_Contract_v1.0.md` — amended §9.6: removed conditional language; Drive/Workspace explicitly not canonical approval receipt store
- `docs/10_meta/ARCHITECTURE_SOURCE_OF_TRUTH.md` — moved blocker #2 to resolved table; section 6 now empty (all blockers resolved)
- `docs/10_meta/ARCHITECTURE_CHANGELOG.md` — added Amendment A3 entry
- `docs/10_meta/architecture_decisions/INDEX.md` — added ADR-004 row and full ADR section
- `docs/INDEX.md` — bumped to rev20 (2026-04-26)
- `docs/LifeOS_Strategic_Corpus.md` — regenerated

## Scope constraints

- closes #32 only
- does not resolve #34 or #35
- does not implement Drive/Workspace advisory ingress
- does not promote `ARCH_Multi_Agent_Communication_Architecture.md` into canon
- preserves Workspace as a non-canonical collaboration and advisory surface
- Google Workspace tooling (`gws`, OAuth credentials, Drive polling, push notifications, service accounts) is not part of the canonical runtime

## Test plan

- [x] Doc stewardship gate: passed (`{"passed": true, "errors": []}`)
- [x] Doc hygiene tests: 6/6 passed
- [x] ARCH_Multi_Agent_Communication_Architecture.md: confirmed draft/proposal-only in SOURCE_OF_TRUTH
- [x] No canonical surface claims Drive is canonical operational state, approval store, or advisory ingress

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by marcusglee11** [comment]
Squash-merged to main as c7df9863 (runtime_status refresh chore: 9923e824). CI: all workflows passed. Quality Gate: PASS with advisory failures (mypy, markdownlint MD013 waived, yamllint). Closes #32.
